# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GourmetApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AlamofireImage'

  # Pods for GourmetApp

  target 'GourmetAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GourmetAppUITests' do
    # Pods for testing
  end
	
end
