platform :ios, '17.5'  # プロジェクト全体のiOSターゲットを17.5に設定

target 'GourmetApp' do
  use_frameworks!
  pod 'AlamofireImage'

  target 'GourmetAppTests' do
    inherit! :search_paths
  end

  target 'GourmetAppUITests' do
  end

end

# 追加部分: すべてのPodのiOSターゲットを17.5に設定
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.5'
    end
  end
end
